# Generated by Django 2.1.9 on 2019-06-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='finaldate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='initdate',
            field=models.DateTimeField(null=True),
        ),
    ]
