# Generated by Django 2.1.9 on 2019-06-27 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190626_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='finaldate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='initdate',
            field=models.DateTimeField(blank=True),
        ),
    ]
