# Generated by Django 2.1.9 on 2019-06-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190626_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='finaldate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='initdate',
            field=models.DateTimeField(),
        ),
    ]
