# Generated by Django 2.1.9 on 2019-06-29 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190628_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='course',
            field=models.TextField(),
        ),
    ]
