# Generated by Django 2.1.9 on 2019-06-29 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190628_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='finaldate',
        ),
        migrations.RemoveField(
            model_name='project',
            name='initdate',
        ),
    ]
