# Generated by Django 2.1.9 on 2019-06-29 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190628_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='finaldate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='initdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
