# Generated by Django 2.1.9 on 2019-06-29 01:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_auto_20190628_2234'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Experience',
        ),
    ]
