# Generated by Django 2.1.9 on 2019-06-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190628_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='course',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='formation',
            name='institution',
            field=models.CharField(max_length=100),
        ),
    ]
