# Generated by Django 2.1.9 on 2019-06-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190628_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='ocupation',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
